// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChbv01YRN_GF_tsQsq4RxlWX1QE33mFPA',
    appId: '1:356718052970:web:af4d20791c00d906d7ac13',
    messagingSenderId: '356718052970',
    projectId: 'fir-project-o1',
    authDomain: 'fir-project-o1.firebaseapp.com',
    storageBucket: 'fir-project-o1.firebasestorage.app',
    measurementId: 'G-BM8K9910VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1jot7rZaWYQznV0CnKCZfSiDv0S34wY',
    appId: '1:356718052970:android:3ba1f53213afe14ad7ac13',
    messagingSenderId: '356718052970',
    projectId: 'fir-project-o1',
    storageBucket: 'fir-project-o1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3pyZG3wfFWhvsiSBAnIejjUUbWd8Pwk',
    appId: '1:356718052970:ios:cd13d97cef1569c1d7ac13',
    messagingSenderId: '356718052970',
    projectId: 'fir-project-o1',
    storageBucket: 'fir-project-o1.firebasestorage.app',
    iosClientId: '356718052970-u09f72n8bv7a0ppea3hl91nsqt0ngp98.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd3pyZG3wfFWhvsiSBAnIejjUUbWd8Pwk',
    appId: '1:356718052970:ios:cd13d97cef1569c1d7ac13',
    messagingSenderId: '356718052970',
    projectId: 'fir-project-o1',
    storageBucket: 'fir-project-o1.firebasestorage.app',
    iosClientId: '356718052970-u09f72n8bv7a0ppea3hl91nsqt0ngp98.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChbv01YRN_GF_tsQsq4RxlWX1QE33mFPA',
    appId: '1:356718052970:web:0ad343abcb374e79d7ac13',
    messagingSenderId: '356718052970',
    projectId: 'fir-project-o1',
    authDomain: 'fir-project-o1.firebaseapp.com',
    storageBucket: 'fir-project-o1.firebasestorage.app',
    measurementId: 'G-SSLD578KTW',
  );
}
